petabridge/petabridge-dotnet-new

RELEASE_NOTES.md

* Added .gitignore file to the Petabridge.Library template
* Added a sample Apache 2 `LICENSE` file to the template
* Added `AssemblyInfo` stage in order to sync `RELEASE_NOTES.md` with `common.props`; now you only need to update the assembly version of your projects inside `RELEASE_NOTES.md`.

added release_notes for 0.1.2

---

RELEASE_NOTES.md

* [`build.fsx` can not automatically detect TeamCity and toggle TC formatting on and off for XUnit2 test runs](https://github.com/petabridge/petabridge-dotnet-new/pull/19).
* [U]pdated XUnit2 target version to 2.3.0 stable](https://github.com/petabridge/petabridge-dotnet-new/pull/20).

added v0.1.3 release notes

---

.gitignore
RELEASE_NOTES.md
src/Content/Petabridge.Library/README.md
src/Content/Petabridge.Library/build.fsx
src/Content/Petabridge.Library/build.ps1
src/Content/Petabridge.Library/build.sh
src/Content/Petabridge.Library/serve-docs.cmd
src/Content/Petabridge.Library/serve-docs.ps1
src/Content/Petabridge.Library/src/Petabridge.Library.Tests.Performance/Petabridge.Library.Tests.Performance.csproj
src/Content/Petabridge.Library/src/Petabridge.Library.Tests/Petabridge.Library.Tests.csproj
src/Content/Petabridge.Library/src/Petabridge.Library/Petabridge.Library.csproj
src/Content/Petabridge.Library/src/common.props

* [Upgrade template to .NET Standard 2.0](https://github.com/petabridge/petabridge-dotnet-new/issues/28).
* [See the full v0.2.0 change set here](https://github.com/petabridge/petabridge-dotnet-new/milestone/1).

Petabridge.Templates v0.2.0

---

RELEASE_NOTES.md

This is a major update to the `Petabridge.Library` `dotnet new` template; most notably it enables .NET Core execution of performance tests using [NBench v1.2.1](https://github.com/petabridge/NBench#running-nbench-tests-with-dotnet-nbench) and the new `dotnet nbench` tool. In addition, we've fixed a number of issues related to DocFx output.
* [Update template to support NBench for .NET Standard and .NET Core](https://github.com/petabridge/petabridge-dotnet-new/issues/24) - also automatically runs NBench now as part of the `./build.cmd all` or `./build.sh all` invocations.
* [DocFx: fix searchbar on IIS](https://github.com/petabridge/petabridge-dotnet-new/issues/54)
* [DocFx: add support for sitemaps](https://github.com/petabridge/petabridge-dotnet-new/issues/47)
* [DocFx: Bug: API …

added v0.3.0 release notes

---

RELEASE_NOTES.md

Fixed a minor issue with `build.sh` not working correctly out of the box due to an unexpected parameter in `dotnet-install.sh`.

v0.3.1 Release Notes

---

RELEASE_NOTES.md
src/Content/Petabridge.Library/src/common.props

Puts an end to those annoying downgrade warnings: https://github.com/petabridge/NBench/issues/246

Upgrade to NBench v1.2.2

---

RELEASE_NOTES.md

* Fixed a minor issue with `build.sh` not working correctly out of the box due to an unexpected parameter in `dotnet-install.sh`.
* Upgraded to NBench v1.2.2 to avoid NuGet package downgrade warnings.

finalized v0.3.1 release notes

---

RELEASE_NOTES.md
build.sh
src/Content/Petabridge.Library/build.sh
src/Content/Petabridge.Library/src/common.props

* Fixed a minor issue with `build.sh` not working correctly out of the box due to an unexpected parameter in `dotnet-install.sh`.
* Upgraded to NBench v1.2.2 to avoid NuGet package downgrade warnings.

v0.3.1 Release

---

RELEASE_NOTES.md
build.fsx
src/Content/Petabridge.Library/build.fsx
src/Content/Petabridge.Library/src/Petabridge.Library.Tests.Performance/Petabridge.Library.Tests.Performance.csproj

made the pre-release version numbering system use the current DateTime.UtcNow.Ticks for numbering beta releases if TC environment vars aren't available

Improve pre-release system

---

RELEASE_NOTES.md

* Upgraded all new projects to use .NET Core 2.1;
* Migrated testing system to use XUnit 2.4.1 and the 15.9.0 version of the Microsoft Test SDK;
* [Migrated all tests to execute via `dotnet test`](https://github.com/petabridge/petabridge-dotnet-new/pull/73), since `dotnet xunit` is now officially deprecated;
* [Added code-signing for all NuGet packages via SignService](https://github.com/petabridge/petabridge-dotnet-new/issues/72); and
* Improved the `nugetprerelease=dev` system such that it can now generate beta version numbers incrementally using the `DateTime.UtcNow.Ticks` value.
For the [full set of changes in `Petabridge.Templates` v0.4.0, click here](https://github.com/petabridge/petabridge-dotnet-new/milestone/4).

added v0.4.0 release notes

---

RELEASE_NOTES.md
build.fsx
build.ps1
build.sh
src/Content/Petabridge.Library/README.md
src/Content/Petabridge.Library/appsettings.json
src/Content/Petabridge.Library/build.fsx
src/Content/Petabridge.Library/build.ps1
src/Content/Petabridge.Library/build.sh
src/Content/Petabridge.Library/src/Petabridge.Library.Tests.Performance/Petabridge.Library.Tests.Performance.csproj
src/Content/Petabridge.Library/src/Petabridge.Library.Tests/Petabridge.Library.Tests.csproj
src/Content/Petabridge.Library/src/common.props

* Upgraded all new projects to use .NET Core 2.1;
* Migrated testing system to use XUnit 2.4.1 and the 15.9.0 version of the Microsoft Test SDK;
* [Migrated all tests to execute via `dotnet test`](https://github.com/petabridge/petabridge-dotnet-new/pull/73), since `dotnet xunit` is now officially deprecated;
* [Added code-signing for all NuGet packages via SignService](https://github.com/petabridge/petabridge-dotnet-new/issues/72); and
* Improved the `nugetprerelease=dev` system such that it can now generate beta version numbers incrementally using the `DateTime.UtcNow.Ticks` value.
For the [full set of changes in `Petabridge.Templates` v0.4.0, click here](https://github.com/petabridge/petabridge-dotnet-new/milestone/4).

v0.4.0 Production Release

---

RELEASE_NOTES.md
src/Content/Petabridge.Library/build.fsx
src/Content/Petabridge.Library/build.ps1
src/Content/Petabridge.Library/build.sh

* Fixed an issue with the `dotnet test` stage that caused it to prematurely fail, rather than run all the way to completion.
* Added DocFx support to `build.sh` and bumped DocFx version to 2.40.5

v0.4.1 Release

---

RELEASE_NOTES.md

* [Fixed: Need to return non-zero exit code when NBench or XUnit tests fail](https://github.com/petabridge/petabridge-dotnet-new/issues/86).

Added v0.4.3 release notes

---

RELEASE_NOTES.md
src/Content/Petabridge.Library/build.fsx

* [Fixed: Need to return non-zero exit code when NBench or XUnit tests fail](https://github.com/petabridge/petabridge-dotnet-new/issues/86).

v0.4.3 Release

---

RELEASE_NOTES.md
azurepipelines-release.yaml

`Petabridge.Templates` now comes with default [Azure DevOps Pipelines YAML files](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema), found in the `/build-system` folder in each new project created via the `pb-lib` `dotnet new` template.
There are three files total:
* `linux-pr-validation.yaml` runs the `build.sh all` command for pull requests on hosted Ubuntu 16.04 VMs.
* `windows-pr-validation.yaml` runs the `build.cmd all` command for pull requested on hosted Windows Server 2016 VMs.
* `windows-release.yaml` runs the full code signing and publication package for your project, plus it creates an automatic release on Github afterwards including all of the signed build artifacts.

added v0.5.0 release notes

---

RELEASE_NOTES.md

**Bugfix Release for Petabridge.Templates v0.5.0**
* Fixed Azure Pipelines YAML - now properly supports build triggers and test reporting.
* Modified `RunTests` task to emit `vtx` files for use in Azure Pipelines. TeamCity integration still works.
* Removed separate `Restore` phase from builds since `dotnet build` handles this implicitly now.

added v0.5.1 release notes

---

RELEASE_NOTES.md
src/Content/Petabridge.Library/build.fsx

**Bugfix Release for Petabridge.Templates v0.5.0**
* Removed unnecessary `RestorePackages` step from `DocFx` build pipeline

v0.5.2 Production Release

---

RELEASE_NOTES.md

**Bugfix Release for Petabridge.Templates v0.5.0**
* [Disabled PR validation for release builds](https://github.com/petabridge/petabridge-dotnet-new/issues/106).
* [Added nightly build template](https://github.com/petabridge/petabridge-dotnet-new/issues/107).
* [Always bundle NuGet packages as artifacts](https://github.com/petabridge/petabridge-dotnet-new/issues/105).

added 0.5.3 release notes

---

RELEASE_NOTES.md
src/Content/Petabridge.Library/build-system/azure-pipeline.template.yaml
src/Content/Petabridge.Library/build-system/nightly-builds.yaml
src/Content/Petabridge.Library/build-system/windows-release.yaml
src/Content/Petabridge.Library/build.fsx

**Bugfix Release for Petabridge.Templates v0.5.0**
* [Disabled PR validation for release builds](https://github.com/petabridge/petabridge-dotnet-new/issues/106).
* [Added nightly build template](https://github.com/petabridge/petabridge-dotnet-new/issues/107).
* [Always bundle NuGet packages as artifacts](https://github.com/petabridge/petabridge-dotnet-new/issues/105).

v0.5.3 Production Release

---

RELEASE_NOTES.md
src/Petabridge.Templates.csproj

This release fixes issues with [only one of the three templates in `Petabridge.Templates` being accessible during `dotnet new`](https://github.com/petabridge/petabridge-dotnet-new/issues/127).
You can now use the following three templates:
* `dotnet new pb-lib` - creates a .NET Standard 2.0 library with a corresponding unit test project, documentation, and build system.
* `dotnet new pb-akka-cluster` - creates a headless .NET Core 3.0 service that includes full [Akka.NET](https://getakka.net/) clustering support, Docker support, documentation, and build systems.
* `dotnet new pb-akka-web` - does the same as `pb-akka-cluster`, but hosts [Akka.NET](https://getakka.net/) inside an ASP.NET Core 3.0 simple web application.

added v1.0.2 release notes

---

README.md
RELEASE_NOTES.md
src/Petabridge.Templates.csproj

This release fixes issues with [only one of the three templates in `Petabridge.Templates` being accessible during `dotnet new`](https://github.com/petabridge/petabridge-dotnet-new/issues/127).
You can now use the following three templates:
* `dotnet new pb-lib` - creates a .NET Standard 2.0 library with a corresponding unit test project, documentation, and build system.
* `dotnet new pb-akka-cluster` - creates a headless .NET Core 3.0 service that includes full [Akka.NET](https://getakka.net/) clustering support, Docker support, documentation, and build systems.
* `dotnet new pb-akka-web` - does the same as `pb-akka-cluster`, but hosts [Akka.NET](https://getakka.net/) inside an ASP.NET Core 3.0 simple web application.

v1.0.2 Release

---

RELEASE_NOTES.md

- Upgraded dependencies of all templates
- Added SourceLink and NuGet symbol package support to `pb-lib`

added v1.0.5 release notes

---

RELEASE_NOTES.md
src/Petabridge.Templates.csproj

- Upgraded dependencies of all templates;
- Upgraded all templates to .NET Core 3.1;
- Added NBench 2.0 support to `pb-lib` template;
- Updated README documentation to accurately reflect latest content of all templates.

v1.1.0 Release

---

RELEASE_NOTES.md

- Upgraded [`pb-akka-cluster`](https://github.com/petabridge/Petabridge.App) and [`pb-akka-web`](https://github.com/petabridge/Petabridge.App.Web) to both use .NET 5
- Modernized [`pb-akka-cluster`](https://github.com/petabridge/Petabridge.App) and [`pb-akka-web`](https://github.com/petabridge/Petabridge.App.Web) to both [use the best `IHostedService` practices for running Akka.NET services behind the scenes](https://petabridge.com/blog/akkadotnet-ihostedservice/).

v1.2.0 Release

---

RELEASE_NOTES.md
src/Petabridge.Templates.csproj

- Added `.gitattributes` to prevent line endings from being modified upon checkout
- Updated `pr_validation` to run `All` and not `RunTests`
- Added steps to convert `build.cmd` and `build.sh` to executables - a fix for file permission issue.
This worked first time in GitHub Action for `Windows, Ubuntu and MacOs`:

Release 2.0.3
